/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AccessLevel
 */
@JsonAdapter(AccessLevel.Adapter.class)
public enum AccessLevel {
  
  NONE("None"),
  
  VIEW_ACCOUNT("ViewAccount"),
  
  VIEW_CONTACTS("ViewContacts"),
  
  VIEW_FORMS("ViewForms"),
  
  VIEW_TEMPLATES("ViewTemplates"),
  
  VIEW_CAMPAIGNS("ViewCampaigns"),
  
  VIEW_CHANNELS("ViewChannels"),
  
  VIEW_AUTOMATIONS("ViewAutomations"),
  
  VIEW_SURVEYS("ViewSurveys"),
  
  VIEW_SETTINGS("ViewSettings"),
  
  VIEW_BILLING("ViewBilling"),
  
  VIEW_SUB_ACCOUNTS("ViewSubAccounts"),
  
  VIEW_USERS("ViewUsers"),
  
  VIEW_FILES("ViewFiles"),
  
  VIEW_REPORTS("ViewReports"),
  
  MODIFY_ACCOUNT("ModifyAccount"),
  
  MODIFY_CONTACTS("ModifyContacts"),
  
  MODIFY_FORMS("ModifyForms"),
  
  MODIFY_TEMPLATES("ModifyTemplates"),
  
  MODIFY_CAMPAIGNS("ModifyCampaigns"),
  
  MODIFY_CHANNELS("ModifyChannels"),
  
  MODIFY_AUTOMATIONS("ModifyAutomations"),
  
  MODIFY_SURVEYS("ModifySurveys"),
  
  MODIFY_FILES("ModifyFiles"),
  
  EXPORT("Export"),
  
  SEND_SMTP("SendSmtp"),
  
  SEND_SMS("SendSMS"),
  
  MODIFY_SETTINGS("ModifySettings"),
  
  MODIFY_BILLING("ModifyBilling"),
  
  MODIFY_PROFILE("ModifyProfile"),
  
  MODIFY_SUB_ACCOUNTS("ModifySubAccounts"),
  
  MODIFY_USERS("ModifyUsers"),
  
  SECURITY("Security"),
  
  MODIFY_LANGUAGE("ModifyLanguage"),
  
  VIEW_SUPPORT("ViewSupport"),
  
  SEND_HTTP("SendHttp"),
  
  MODIFY2_FA_EMAIL("Modify2FAEmail"),
  
  MODIFY_SUPPORT("ModifySupport"),
  
  VIEW_CUSTOM_FIELDS("ViewCustomFields"),
  
  MODIFY_CUSTOM_FIELDS("ModifyCustomFields"),
  
  MODIFY_WEB_NOTIFICATIONS("ModifyWebNotifications"),
  
  EXTENDED_LOGS("ExtendedLogs"),
  
  VERIFY_EMAILS("VerifyEmails"),
  
  MODIFY2_FA_SMS("Modify2FASms"),
  
  MODIFY_LANDING_PAGES("ModifyLandingPages"),
  
  VIEW_LANDING_PAGES("ViewLandingPages"),
  
  MODIFY_SUPPRESSIONS("ModifySuppressions"),
  
  VIEW_SUPPRESSIONS("ViewSuppressions"),
  
  VIEW_DRAG_DROP_EDITOR("ViewDragDropEditor"),
  
  VIEW_TEMPLATE_EDITOR("ViewTemplateEditor"),
  
  VIEW_AI_TOOLS("ViewAITools");

  private String value;

  AccessLevel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccessLevel fromValue(String value) {
    for (AccessLevel b : AccessLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AccessLevel> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccessLevel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccessLevel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccessLevel.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AccessLevel.fromValue(value);
  }
}

