/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.elasticemail.client.JSON;

/**
 * List of Lists, with detailed data about its contents.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-22T13:34:56.566653Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class ContactsList {
  public static final String SERIALIZED_NAME_LIST_NAME = "ListName";
  @SerializedName(SERIALIZED_NAME_LIST_NAME)
  private String listName;

  public static final String SERIALIZED_NAME_PUBLIC_LIST_I_D = "PublicListID";
  @SerializedName(SERIALIZED_NAME_PUBLIC_LIST_I_D)
  private String publicListID;

  public static final String SERIALIZED_NAME_DATE_ADDED = "DateAdded";
  @SerializedName(SERIALIZED_NAME_DATE_ADDED)
  private OffsetDateTime dateAdded;

  public static final String SERIALIZED_NAME_ALLOW_UNSUBSCRIBE = "AllowUnsubscribe";
  @SerializedName(SERIALIZED_NAME_ALLOW_UNSUBSCRIBE)
  private Boolean allowUnsubscribe;

  public ContactsList() {
  }

  public ContactsList listName(String listName) {
    this.listName = listName;
    return this;
  }

   /**
   * Name of your list.
   * @return listName
  **/
  @javax.annotation.Nullable
  public String getListName() {
    return listName;
  }

  public void setListName(String listName) {
    this.listName = listName;
  }


  public ContactsList publicListID(String publicListID) {
    this.publicListID = publicListID;
    return this;
  }

   /**
   * ID code of list. Please note that this is different from the listid field.
   * @return publicListID
  **/
  @javax.annotation.Nullable
  public String getPublicListID() {
    return publicListID;
  }

  public void setPublicListID(String publicListID) {
    this.publicListID = publicListID;
  }


  public ContactsList dateAdded(OffsetDateTime dateAdded) {
    this.dateAdded = dateAdded;
    return this;
  }

   /**
   * Date of creation in YYYY-MM-DDThh:ii:ss format
   * @return dateAdded
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getDateAdded() {
    return dateAdded;
  }

  public void setDateAdded(OffsetDateTime dateAdded) {
    this.dateAdded = dateAdded;
  }


  public ContactsList allowUnsubscribe(Boolean allowUnsubscribe) {
    this.allowUnsubscribe = allowUnsubscribe;
    return this;
  }

   /**
   * True: Allow unsubscribing from this list. Otherwise, false
   * @return allowUnsubscribe
  **/
  @javax.annotation.Nullable
  public Boolean getAllowUnsubscribe() {
    return allowUnsubscribe;
  }

  public void setAllowUnsubscribe(Boolean allowUnsubscribe) {
    this.allowUnsubscribe = allowUnsubscribe;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactsList contactsList = (ContactsList) o;
    return Objects.equals(this.listName, contactsList.listName) &&
        Objects.equals(this.publicListID, contactsList.publicListID) &&
        Objects.equals(this.dateAdded, contactsList.dateAdded) &&
        Objects.equals(this.allowUnsubscribe, contactsList.allowUnsubscribe);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(listName, publicListID, dateAdded, allowUnsubscribe);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactsList {\n");
    sb.append("    listName: ").append(toIndentedString(listName)).append("\n");
    sb.append("    publicListID: ").append(toIndentedString(publicListID)).append("\n");
    sb.append("    dateAdded: ").append(toIndentedString(dateAdded)).append("\n");
    sb.append("    allowUnsubscribe: ").append(toIndentedString(allowUnsubscribe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ListName");
    openapiFields.add("PublicListID");
    openapiFields.add("DateAdded");
    openapiFields.add("AllowUnsubscribe");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ContactsList
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContactsList.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContactsList is not found in the empty JSON string", ContactsList.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContactsList.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContactsList` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ListName") != null && !jsonObj.get("ListName").isJsonNull()) && !jsonObj.get("ListName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ListName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ListName").toString()));
      }
      if ((jsonObj.get("PublicListID") != null && !jsonObj.get("PublicListID").isJsonNull()) && !jsonObj.get("PublicListID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PublicListID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PublicListID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContactsList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContactsList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContactsList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContactsList.class));

       return (TypeAdapter<T>) new TypeAdapter<ContactsList>() {
           @Override
           public void write(JsonWriter out, ContactsList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContactsList read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ContactsList given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ContactsList
  * @throws IOException if the JSON string is invalid with respect to ContactsList
  */
  public static ContactsList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContactsList.class);
  }

 /**
  * Convert an instance of ContactsList to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

