/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.elasticemail.client.JSON;

/**
 * Settings related to sending emails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-08T09:36:05.709243Z[Etc/UTC]", comments = "Generator version: 7.7.0")
public class SubaccountEmailSettingsPayload {
  public static final String SERIALIZED_NAME_REQUIRES_EMAIL_CREDITS = "RequiresEmailCredits";
  @SerializedName(SERIALIZED_NAME_REQUIRES_EMAIL_CREDITS)
  private Boolean requiresEmailCredits;

  public static final String SERIALIZED_NAME_EMAIL_SIZE_LIMIT = "EmailSizeLimit";
  @SerializedName(SERIALIZED_NAME_EMAIL_SIZE_LIMIT)
  private Integer emailSizeLimit;

  public static final String SERIALIZED_NAME_DAILY_SEND_LIMIT = "DailySendLimit";
  @SerializedName(SERIALIZED_NAME_DAILY_SEND_LIMIT)
  private Integer dailySendLimit;

  public static final String SERIALIZED_NAME_MAX_CONTACTS = "MaxContacts";
  @SerializedName(SERIALIZED_NAME_MAX_CONTACTS)
  private Integer maxContacts;

  public static final String SERIALIZED_NAME_ENABLE_PRIVATE_I_P_PURCHASE = "EnablePrivateIPPurchase";
  @SerializedName(SERIALIZED_NAME_ENABLE_PRIVATE_I_P_PURCHASE)
  private Boolean enablePrivateIPPurchase;

  public static final String SERIALIZED_NAME_POOL_NAME = "PoolName";
  @SerializedName(SERIALIZED_NAME_POOL_NAME)
  private String poolName;

  public static final String SERIALIZED_NAME_VALID_SENDER_DOMAIN_ONLY = "ValidSenderDomainOnly";
  @SerializedName(SERIALIZED_NAME_VALID_SENDER_DOMAIN_ONLY)
  private Boolean validSenderDomainOnly;

  public SubaccountEmailSettingsPayload() {
  }

  public SubaccountEmailSettingsPayload requiresEmailCredits(Boolean requiresEmailCredits) {
    this.requiresEmailCredits = requiresEmailCredits;
    return this;
  }

  /**
   * True, if Account needs credits to send emails. Otherwise, false
   * @return requiresEmailCredits
   */
  @javax.annotation.Nullable
  public Boolean getRequiresEmailCredits() {
    return requiresEmailCredits;
  }

  public void setRequiresEmailCredits(Boolean requiresEmailCredits) {
    this.requiresEmailCredits = requiresEmailCredits;
  }


  public SubaccountEmailSettingsPayload emailSizeLimit(Integer emailSizeLimit) {
    this.emailSizeLimit = emailSizeLimit;
    return this;
  }

  /**
   * Maximum size of email including attachments in MB&#39;s
   * @return emailSizeLimit
   */
  @javax.annotation.Nullable
  public Integer getEmailSizeLimit() {
    return emailSizeLimit;
  }

  public void setEmailSizeLimit(Integer emailSizeLimit) {
    this.emailSizeLimit = emailSizeLimit;
  }


  public SubaccountEmailSettingsPayload dailySendLimit(Integer dailySendLimit) {
    this.dailySendLimit = dailySendLimit;
    return this;
  }

  /**
   * Amount of emails Account can send daily
   * @return dailySendLimit
   */
  @javax.annotation.Nullable
  public Integer getDailySendLimit() {
    return dailySendLimit;
  }

  public void setDailySendLimit(Integer dailySendLimit) {
    this.dailySendLimit = dailySendLimit;
  }


  public SubaccountEmailSettingsPayload maxContacts(Integer maxContacts) {
    this.maxContacts = maxContacts;
    return this;
  }

  /**
   * Maximum number of contacts the Account can have. 0 means that parent account&#39;s limit is used.
   * @return maxContacts
   */
  @javax.annotation.Nullable
  public Integer getMaxContacts() {
    return maxContacts;
  }

  public void setMaxContacts(Integer maxContacts) {
    this.maxContacts = maxContacts;
  }


  public SubaccountEmailSettingsPayload enablePrivateIPPurchase(Boolean enablePrivateIPPurchase) {
    this.enablePrivateIPPurchase = enablePrivateIPPurchase;
    return this;
  }

  /**
   * Can the SubAccount purchase Private IP for themselves
   * @return enablePrivateIPPurchase
   */
  @javax.annotation.Nullable
  public Boolean getEnablePrivateIPPurchase() {
    return enablePrivateIPPurchase;
  }

  public void setEnablePrivateIPPurchase(Boolean enablePrivateIPPurchase) {
    this.enablePrivateIPPurchase = enablePrivateIPPurchase;
  }


  public SubaccountEmailSettingsPayload poolName(String poolName) {
    this.poolName = poolName;
    return this;
  }

  /**
   * Name of your custom IP Pool to be used in the sending process
   * @return poolName
   */
  @javax.annotation.Nullable
  public String getPoolName() {
    return poolName;
  }

  public void setPoolName(String poolName) {
    this.poolName = poolName;
  }


  public SubaccountEmailSettingsPayload validSenderDomainOnly(Boolean validSenderDomainOnly) {
    this.validSenderDomainOnly = validSenderDomainOnly;
    return this;
  }

  /**
   * Get validSenderDomainOnly
   * @return validSenderDomainOnly
   */
  @javax.annotation.Nullable
  public Boolean getValidSenderDomainOnly() {
    return validSenderDomainOnly;
  }

  public void setValidSenderDomainOnly(Boolean validSenderDomainOnly) {
    this.validSenderDomainOnly = validSenderDomainOnly;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubaccountEmailSettingsPayload subaccountEmailSettingsPayload = (SubaccountEmailSettingsPayload) o;
    return Objects.equals(this.requiresEmailCredits, subaccountEmailSettingsPayload.requiresEmailCredits) &&
        Objects.equals(this.emailSizeLimit, subaccountEmailSettingsPayload.emailSizeLimit) &&
        Objects.equals(this.dailySendLimit, subaccountEmailSettingsPayload.dailySendLimit) &&
        Objects.equals(this.maxContacts, subaccountEmailSettingsPayload.maxContacts) &&
        Objects.equals(this.enablePrivateIPPurchase, subaccountEmailSettingsPayload.enablePrivateIPPurchase) &&
        Objects.equals(this.poolName, subaccountEmailSettingsPayload.poolName) &&
        Objects.equals(this.validSenderDomainOnly, subaccountEmailSettingsPayload.validSenderDomainOnly);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiresEmailCredits, emailSizeLimit, dailySendLimit, maxContacts, enablePrivateIPPurchase, poolName, validSenderDomainOnly);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubaccountEmailSettingsPayload {\n");
    sb.append("    requiresEmailCredits: ").append(toIndentedString(requiresEmailCredits)).append("\n");
    sb.append("    emailSizeLimit: ").append(toIndentedString(emailSizeLimit)).append("\n");
    sb.append("    dailySendLimit: ").append(toIndentedString(dailySendLimit)).append("\n");
    sb.append("    maxContacts: ").append(toIndentedString(maxContacts)).append("\n");
    sb.append("    enablePrivateIPPurchase: ").append(toIndentedString(enablePrivateIPPurchase)).append("\n");
    sb.append("    poolName: ").append(toIndentedString(poolName)).append("\n");
    sb.append("    validSenderDomainOnly: ").append(toIndentedString(validSenderDomainOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RequiresEmailCredits");
    openapiFields.add("EmailSizeLimit");
    openapiFields.add("DailySendLimit");
    openapiFields.add("MaxContacts");
    openapiFields.add("EnablePrivateIPPurchase");
    openapiFields.add("PoolName");
    openapiFields.add("ValidSenderDomainOnly");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubaccountEmailSettingsPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubaccountEmailSettingsPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubaccountEmailSettingsPayload is not found in the empty JSON string", SubaccountEmailSettingsPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubaccountEmailSettingsPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubaccountEmailSettingsPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("PoolName") != null && !jsonObj.get("PoolName").isJsonNull()) && !jsonObj.get("PoolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PoolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PoolName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubaccountEmailSettingsPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubaccountEmailSettingsPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubaccountEmailSettingsPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubaccountEmailSettingsPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<SubaccountEmailSettingsPayload>() {
           @Override
           public void write(JsonWriter out, SubaccountEmailSettingsPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubaccountEmailSettingsPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubaccountEmailSettingsPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubaccountEmailSettingsPayload
   * @throws IOException if the JSON string is invalid with respect to SubaccountEmailSettingsPayload
   */
  public static SubaccountEmailSettingsPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubaccountEmailSettingsPayload.class);
  }

  /**
   * Convert an instance of SubaccountEmailSettingsPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

