/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import java.util.Arrays;
import com.elasticemail.model.BodyPart;
import com.elasticemail.model.TemplateScope;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * New template object
 */
@ApiModel(description = "New template object")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-10T10:01:55.764174Z[Etc/UTC]")
public class TemplatePayload {
  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUBJECT = "Subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_BODY = "Body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private List<BodyPart> body = null;

  public static final String SERIALIZED_NAME_TEMPLATE_SCOPE = "TemplateScope";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_SCOPE)
  private TemplateScope templateScope = TemplateScope.PERSONAL;


  public TemplatePayload name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Template name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Template name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public TemplatePayload subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Default subject of email.
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Hello!", value = "Default subject of email.")

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public TemplatePayload body(List<BodyPart> body) {
    
    this.body = body;
    return this;
  }

  public TemplatePayload addBodyItem(BodyPart bodyItem) {
    if (this.body == null) {
      this.body = new ArrayList<BodyPart>();
    }
    this.body.add(bodyItem);
    return this;
  }

   /**
   * Email content of this template
   * @return body
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email content of this template")

  public List<BodyPart> getBody() {
    return body;
  }


  public void setBody(List<BodyPart> body) {
    this.body = body;
  }


  public TemplatePayload templateScope(TemplateScope templateScope) {
    
    this.templateScope = templateScope;
    return this;
  }

   /**
   * Get templateScope
   * @return templateScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateScope getTemplateScope() {
    return templateScope;
  }


  public void setTemplateScope(TemplateScope templateScope) {
    this.templateScope = templateScope;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatePayload templatePayload = (TemplatePayload) o;
    return Objects.equals(this.name, templatePayload.name) &&
        Objects.equals(this.subject, templatePayload.subject) &&
        Objects.equals(this.body, templatePayload.body) &&
        Objects.equals(this.templateScope, templatePayload.templateScope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, subject, body, templateScope);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatePayload {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    templateScope: ").append(toIndentedString(templateScope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

