/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * List of transactional recipients
 */
@ApiModel(description = "List of transactional recipients")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-25T13:02:35.289764Z[Etc/UTC]")
public class TransactionalRecipient {
  public static final String SERIALIZED_NAME_TO = "To";
  @SerializedName(SERIALIZED_NAME_TO)
  private List<String> to = null;

  public static final String SERIALIZED_NAME_C_C = "CC";
  @SerializedName(SERIALIZED_NAME_C_C)
  private List<String> CC = null;

  public static final String SERIALIZED_NAME_B_C_C = "BCC";
  @SerializedName(SERIALIZED_NAME_B_C_C)
  private List<String> BCC = null;


  public TransactionalRecipient to(List<String> to) {
    
    this.to = to;
    return this;
  }

  public TransactionalRecipient addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<String>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * List of recipients (visible to others)
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of recipients (visible to others)")

  public List<String> getTo() {
    return to;
  }


  public void setTo(List<String> to) {
    this.to = to;
  }


  public TransactionalRecipient CC(List<String> CC) {
    
    this.CC = CC;
    return this;
  }

  public TransactionalRecipient addCCItem(String CCItem) {
    if (this.CC == null) {
      this.CC = new ArrayList<String>();
    }
    this.CC.add(CCItem);
    return this;
  }

   /**
   * List of Carbon Copy recipients (visible to others)
   * @return CC
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of Carbon Copy recipients (visible to others)")

  public List<String> getCC() {
    return CC;
  }


  public void setCC(List<String> CC) {
    this.CC = CC;
  }


  public TransactionalRecipient BCC(List<String> BCC) {
    
    this.BCC = BCC;
    return this;
  }

  public TransactionalRecipient addBCCItem(String BCCItem) {
    if (this.BCC == null) {
      this.BCC = new ArrayList<String>();
    }
    this.BCC.add(BCCItem);
    return this;
  }

   /**
   * List of Blind Carbon Copy recipients (hidden from other recipients)
   * @return BCC
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of Blind Carbon Copy recipients (hidden from other recipients)")

  public List<String> getBCC() {
    return BCC;
  }


  public void setBCC(List<String> BCC) {
    this.BCC = BCC;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionalRecipient transactionalRecipient = (TransactionalRecipient) o;
    return Objects.equals(this.to, transactionalRecipient.to) &&
        Objects.equals(this.CC, transactionalRecipient.CC) &&
        Objects.equals(this.BCC, transactionalRecipient.BCC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, CC, BCC);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionalRecipient {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    CC: ").append(toIndentedString(CC)).append("\n");
    sb.append("    BCC: ").append(toIndentedString(BCC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

