/*
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elasticemail.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.elasticemail.client.JSON;

/**
 * Notification webhook setting
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-27T04:05:08.905783Z[Etc/UTC]", comments = "Generator version: 7.11.0")
public class Webhook {
  public static final String SERIALIZED_NAME_WEBHOOK_I_D = "WebhookID";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_I_D)
  @javax.annotation.Nullable
  private String webhookID;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DATE_CREATED = "DateCreated";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  @javax.annotation.Nullable
  private OffsetDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_UPDATED = "DateUpdated";
  @SerializedName(SERIALIZED_NAME_DATE_UPDATED)
  @javax.annotation.Nullable
  private OffsetDateTime dateUpdated;

  public static final String SERIALIZED_NAME_U_R_L = "URL";
  @SerializedName(SERIALIZED_NAME_U_R_L)
  @javax.annotation.Nullable
  private String URL;

  public static final String SERIALIZED_NAME_NOTIFY_ONCE_PER_EMAIL = "NotifyOncePerEmail";
  @SerializedName(SERIALIZED_NAME_NOTIFY_ONCE_PER_EMAIL)
  @javax.annotation.Nullable
  private Boolean notifyOncePerEmail;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_SENT = "NotificationForSent";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_SENT)
  @javax.annotation.Nullable
  private Boolean notificationForSent;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_OPENED = "NotificationForOpened";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_OPENED)
  @javax.annotation.Nullable
  private Boolean notificationForOpened;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_CLICKED = "NotificationForClicked";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_CLICKED)
  @javax.annotation.Nullable
  private Boolean notificationForClicked;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_UNSUBSCRIBED = "NotificationForUnsubscribed";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_UNSUBSCRIBED)
  @javax.annotation.Nullable
  private Boolean notificationForUnsubscribed;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_ABUSE_REPORT = "NotificationForAbuseReport";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_ABUSE_REPORT)
  @javax.annotation.Nullable
  private Boolean notificationForAbuseReport;

  public static final String SERIALIZED_NAME_NOTIFICATION_FOR_ERROR = "NotificationForError";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_FOR_ERROR)
  @javax.annotation.Nullable
  private Boolean notificationForError;

  public static final String SERIALIZED_NAME_IS_ENABLED = "IsEnabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  @javax.annotation.Nullable
  private Boolean isEnabled;

  public Webhook() {
  }

  public Webhook webhookID(@javax.annotation.Nullable String webhookID) {
    this.webhookID = webhookID;
    return this;
  }

  /**
   * Public webhook ID
   * @return webhookID
   */
  @javax.annotation.Nullable
  public String getWebhookID() {
    return webhookID;
  }

  public void setWebhookID(@javax.annotation.Nullable String webhookID) {
    this.webhookID = webhookID;
  }


  public Webhook name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Filename
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Webhook dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Creation date.
   * @return dateCreated
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public Webhook dateUpdated(@javax.annotation.Nullable OffsetDateTime dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Last change date
   * @return dateUpdated
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(@javax.annotation.Nullable OffsetDateTime dateUpdated) {
    this.dateUpdated = dateUpdated;
  }


  public Webhook URL(@javax.annotation.Nullable String URL) {
    this.URL = URL;
    return this;
  }

  /**
   * URL of notification.
   * @return URL
   */
  @javax.annotation.Nullable
  public String getURL() {
    return URL;
  }

  public void setURL(@javax.annotation.Nullable String URL) {
    this.URL = URL;
  }


  public Webhook notifyOncePerEmail(@javax.annotation.Nullable Boolean notifyOncePerEmail) {
    this.notifyOncePerEmail = notifyOncePerEmail;
    return this;
  }

  /**
   * Get notifyOncePerEmail
   * @return notifyOncePerEmail
   */
  @javax.annotation.Nullable
  public Boolean getNotifyOncePerEmail() {
    return notifyOncePerEmail;
  }

  public void setNotifyOncePerEmail(@javax.annotation.Nullable Boolean notifyOncePerEmail) {
    this.notifyOncePerEmail = notifyOncePerEmail;
  }


  public Webhook notificationForSent(@javax.annotation.Nullable Boolean notificationForSent) {
    this.notificationForSent = notificationForSent;
    return this;
  }

  /**
   * Get notificationForSent
   * @return notificationForSent
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForSent() {
    return notificationForSent;
  }

  public void setNotificationForSent(@javax.annotation.Nullable Boolean notificationForSent) {
    this.notificationForSent = notificationForSent;
  }


  public Webhook notificationForOpened(@javax.annotation.Nullable Boolean notificationForOpened) {
    this.notificationForOpened = notificationForOpened;
    return this;
  }

  /**
   * Get notificationForOpened
   * @return notificationForOpened
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForOpened() {
    return notificationForOpened;
  }

  public void setNotificationForOpened(@javax.annotation.Nullable Boolean notificationForOpened) {
    this.notificationForOpened = notificationForOpened;
  }


  public Webhook notificationForClicked(@javax.annotation.Nullable Boolean notificationForClicked) {
    this.notificationForClicked = notificationForClicked;
    return this;
  }

  /**
   * Get notificationForClicked
   * @return notificationForClicked
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForClicked() {
    return notificationForClicked;
  }

  public void setNotificationForClicked(@javax.annotation.Nullable Boolean notificationForClicked) {
    this.notificationForClicked = notificationForClicked;
  }


  public Webhook notificationForUnsubscribed(@javax.annotation.Nullable Boolean notificationForUnsubscribed) {
    this.notificationForUnsubscribed = notificationForUnsubscribed;
    return this;
  }

  /**
   * Get notificationForUnsubscribed
   * @return notificationForUnsubscribed
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForUnsubscribed() {
    return notificationForUnsubscribed;
  }

  public void setNotificationForUnsubscribed(@javax.annotation.Nullable Boolean notificationForUnsubscribed) {
    this.notificationForUnsubscribed = notificationForUnsubscribed;
  }


  public Webhook notificationForAbuseReport(@javax.annotation.Nullable Boolean notificationForAbuseReport) {
    this.notificationForAbuseReport = notificationForAbuseReport;
    return this;
  }

  /**
   * Get notificationForAbuseReport
   * @return notificationForAbuseReport
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForAbuseReport() {
    return notificationForAbuseReport;
  }

  public void setNotificationForAbuseReport(@javax.annotation.Nullable Boolean notificationForAbuseReport) {
    this.notificationForAbuseReport = notificationForAbuseReport;
  }


  public Webhook notificationForError(@javax.annotation.Nullable Boolean notificationForError) {
    this.notificationForError = notificationForError;
    return this;
  }

  /**
   * Get notificationForError
   * @return notificationForError
   */
  @javax.annotation.Nullable
  public Boolean getNotificationForError() {
    return notificationForError;
  }

  public void setNotificationForError(@javax.annotation.Nullable Boolean notificationForError) {
    this.notificationForError = notificationForError;
  }


  public Webhook isEnabled(@javax.annotation.Nullable Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Get isEnabled
   * @return isEnabled
   */
  @javax.annotation.Nullable
  public Boolean getIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(@javax.annotation.Nullable Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhook webhook = (Webhook) o;
    return Objects.equals(this.webhookID, webhook.webhookID) &&
        Objects.equals(this.name, webhook.name) &&
        Objects.equals(this.dateCreated, webhook.dateCreated) &&
        Objects.equals(this.dateUpdated, webhook.dateUpdated) &&
        Objects.equals(this.URL, webhook.URL) &&
        Objects.equals(this.notifyOncePerEmail, webhook.notifyOncePerEmail) &&
        Objects.equals(this.notificationForSent, webhook.notificationForSent) &&
        Objects.equals(this.notificationForOpened, webhook.notificationForOpened) &&
        Objects.equals(this.notificationForClicked, webhook.notificationForClicked) &&
        Objects.equals(this.notificationForUnsubscribed, webhook.notificationForUnsubscribed) &&
        Objects.equals(this.notificationForAbuseReport, webhook.notificationForAbuseReport) &&
        Objects.equals(this.notificationForError, webhook.notificationForError) &&
        Objects.equals(this.isEnabled, webhook.isEnabled);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhookID, name, dateCreated, dateUpdated, URL, notifyOncePerEmail, notificationForSent, notificationForOpened, notificationForClicked, notificationForUnsubscribed, notificationForAbuseReport, notificationForError, isEnabled);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhook {\n");
    sb.append("    webhookID: ").append(toIndentedString(webhookID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    URL: ").append(toIndentedString(URL)).append("\n");
    sb.append("    notifyOncePerEmail: ").append(toIndentedString(notifyOncePerEmail)).append("\n");
    sb.append("    notificationForSent: ").append(toIndentedString(notificationForSent)).append("\n");
    sb.append("    notificationForOpened: ").append(toIndentedString(notificationForOpened)).append("\n");
    sb.append("    notificationForClicked: ").append(toIndentedString(notificationForClicked)).append("\n");
    sb.append("    notificationForUnsubscribed: ").append(toIndentedString(notificationForUnsubscribed)).append("\n");
    sb.append("    notificationForAbuseReport: ").append(toIndentedString(notificationForAbuseReport)).append("\n");
    sb.append("    notificationForError: ").append(toIndentedString(notificationForError)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("WebhookID");
    openapiFields.add("Name");
    openapiFields.add("DateCreated");
    openapiFields.add("DateUpdated");
    openapiFields.add("URL");
    openapiFields.add("NotifyOncePerEmail");
    openapiFields.add("NotificationForSent");
    openapiFields.add("NotificationForOpened");
    openapiFields.add("NotificationForClicked");
    openapiFields.add("NotificationForUnsubscribed");
    openapiFields.add("NotificationForAbuseReport");
    openapiFields.add("NotificationForError");
    openapiFields.add("IsEnabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Webhook
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Webhook.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Webhook is not found in the empty JSON string", Webhook.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Webhook.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Webhook` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("WebhookID") != null && !jsonObj.get("WebhookID").isJsonNull()) && !jsonObj.get("WebhookID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `WebhookID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("WebhookID").toString()));
      }
      if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      if ((jsonObj.get("URL") != null && !jsonObj.get("URL").isJsonNull()) && !jsonObj.get("URL").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `URL` to be a primitive type in the JSON string but got `%s`", jsonObj.get("URL").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Webhook.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Webhook' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Webhook> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Webhook.class));

       return (TypeAdapter<T>) new TypeAdapter<Webhook>() {
           @Override
           public void write(JsonWriter out, Webhook value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Webhook read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Webhook given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Webhook
   * @throws IOException if the JSON string is invalid with respect to Webhook
   */
  public static Webhook fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Webhook.class);
  }

  /**
   * Convert an instance of Webhook to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

